### ISSUE TITLE
Clicking into searchbar should display options

### ISSUE THREAD

**Issue by pjames27** [codexstanford/codex-insurance-fullstack#26]
The dropdown list of services should be displayed as soon as the user clicks into the searchbar - they shouldn't have to wait for additional keyboard input to see the list of services.

**Comment by pfw13** [comment]
The library we use for the search bar supports this only in the latest alpha version. I've updated the code to use this alpha version. Here's the issue discussing this feature on their GitHub: [Link](https://github.com/tailwindlabs/headlessui/discussions/1236). Switching to the alpha might have unknown consequences, like causing bugs somewhere else.
