### ISSUE TITLE
Ensure datasets don't have repeat facts - zniquify

### ISSUE THREAD

**Issue by pjames27** [codexstanford/codex-insurance-fullstack#64]
Currently, the same fact can get written to the dataset multiple times. To avoid this, we should use the epilog.js subroutine [zniquify](http://epilog.stanford.edu/documentation/epilogjs/zniquify.php) after adding facts to a dataset, and certainly before writing datasets to the database.

**Comment by pfw13** [comment]
zniquify is called now before smth is sent to the server. This should be sufficient, i.e., it doesn't seem necessary to call this function in every subroutine that defines more facts.
